---
sudo: false
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.4
env:
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER="yes"
matrix:
  exclude:
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.3.0"
script: bundle exec rake spec
